### ISSUE TITLE
Generic Editor occurence highlight color should be different.

### ISSUE THREAD

**Issue by AObuchow** [AObuchow/Eclipse-Spectrum-Theme#109]
When using the generic editor, the "occurrence" highlight color makes the foreground difficult to read.
![image](https://user-images.githubusercontent.com/10300119/86409770-88cd8a80-bc87-11ea-8027-0049163db361.png)

In this case, it's ` #d4d4d4`.

I believe this is related to:
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=531782
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=521382
- https://github.com/eclipse/eclipse.platform.text/blob/master/org.eclipse.ui.genericeditor/resources/css/dark.css#L17

**Comment by AObuchow** [comment]
So it turns out the following is only to set the color of the occurrences highlight when no presentation reconciler is used.
```CSS
IEclipsePreferences#org-eclipse-ui-editors:org-eclipse-ui-genericeditor {
  preferences:
        'TextOccurrenceIndicationColor=27,98,145'
}
```
Thus, opening a .txt file with the generic editor will use that color preference to mark text occurrences.

For the CSS LS, this is being handled in LSP4E.
