### ISSUE TITLE
Add some extra default color schemes

### ISSUE THREAD

**Issue by AObuchow** [AObuchow/Eclipse-Spectrum-Theme#124]
Since I intend to allow users to save & load color schemes, it makes sense to include some extra default color schemes.
I'm making this bug to track color schemes that I like and might want to include.

**Comment by AObuchow** [comment]
```CSS
ColorScheme {
    --background-color: #1F2531;
    --base-color: #252C3B;
    --accent-color: #D70000;
}
```
![image](https://user-images.githubusercontent.com/10300119/89108018-3fe23080-d403-11ea-92f3-b696adf928bd.png)

Based off of the Godot Editor's color scheme.

**Comment by AObuchow** [comment]
```CSS
ColorScheme {
    --background-color: #0E1014;
    --base-color: #171C26;
    --accent-color: #C4A000;
}
```

![image](https://user-images.githubusercontent.com/10300119/92684527-a9f3cc80-f303-11ea-87cb-5a7bc1d0293c.png)

Similar to above, just darker and with yellow accent

**Comment by AObuchow** [comment]
```CSS
ColorScheme {
    --background-color: #0C141B;
    --base-color: #101C27;
    --accent-color: #D70072;
}
```

![image](https://user-images.githubusercontent.com/10300119/93154774-7a154200-f6d2-11ea-98c3-794ee7cfd078.png)
